### ISSUE TITLE
Initiate React Project 

### ISSUE THREAD

**Issue by shivaylamba** [scaleracademy/twitter-frontend-react#1]
Initialize base react project

**Comment by raghavdhingra** [comment]
I would like to take up the issue @shivaylamba

**Comment by shivaylamba** [comment]
Thanks for your initiative @raghavdhingra, assigning the issue to you

**Comment by shivaylamba** [comment]
Requirements include : 
TypeScript, React, Webpack

**Comment by raghavdhingra** [comment]
Okay, thanks! I will keep it in mind and initialize the current frontend project

**Comment by shivaylamba** [comment]
#2
