### ISSUE TITLE
Bug : Images not loading in initialised project

### ISSUE THREAD

**Issue by shivaylamba** [scaleracademy/twitter-frontend-react#3]
custom.d.ts file required for enabling images to be loaded

**Comment by shivaylamba** [comment]
Alright thanks for the initiative

**Comment by harishfalco** [comment]
Hello Mr.raghavdhingra , Can I solve this issue? I am a beginner trying to contribute to open source.?

**Comment by raghavdhingra** [comment]
@harishfalco Thanks for coming forward. I've already made the PR
You can test that out with different sets of images

**Comment by shivaylamba** [comment]
@harishfalco you can also contribute to other issues, we will have a lot of beginner friendly issues

**Comment by shivaylamba** [comment]
#4 Closing the issue. Thanks @raghavdhingra
