### ISSUE TITLE
Implement Redux with the app

### ISSUE THREAD

**Issue by raghavdhingra** [scaleracademy/twitter-frontend-react#5]
@shivaylamba Can I start implementing the redux within the application?
For the initial step, will implement the root logic, and will discuss the state after the implementation of the root logic

**Comment by shivaylamba** [comment]
Thanks for the issue @raghavdhingra. Yes we can initiate to setup the redux. 
Could you let me know what you do mean by the root logic?

**Comment by raghavdhingra** [comment]
What I mean by the root logic is to initiate a redux template, interface, and architecture to proceed.
After the setup, we can discuss the workflow of the application.
So @shivaylamba Should I start to work upon it?

**Comment by shivaylamba** [comment]
Ok, thanks for the explanation @raghavdhingra. I understand. You can work on setup of the Redux. Will be helpful for future contributors to follow the template used for creation of the redux in the project. We can also update the Readme with the same.

**Comment by shivaylamba** [comment]
@raghavdhingra have assigned you the task for it.
