### ISSUE TITLE
Implement Routing in the Application 

### ISSUE THREAD

**Issue by shivaylamba** [scaleracademy/twitter-frontend-react#6]
Implement Router DOM along with its types.

**Comment by raghavdhingra** [comment]
Hi @shivaylamba!
I was adding the routes within the redux implementation.
Should I make a new PR for it, or continue to work on it?

**Comment by shivaylamba** [comment]
Hi @raghavdhingra thanks for raising this point. You can create a new pull request for the routes implementation.

**Comment by shivaylamba** [comment]
thanks
